# Generated by Django 5.2.12 on 2026-03-18 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('activation_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('key_expires_at', models.DateTimeField()),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
